all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    proxmox:
      hosts:
        proxmox-node:
          ansible_host: 10.0.20.2
          ansible_user: root

    nas:
      hosts:
        ugreennas:
          ansible_host: 10.0.20.X
          ansible_user: admin
